name: release-packages

on:
  push:
    tags: [ "v*" ]

env:
  REGISTRY_SERVER_ADDRESS: ghcr.io/miracleeverywhere/dst-management-platform-api

jobs:
  build-binary:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Go 1.25.4
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.4

      - name: build-linux
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: matrix.os == 'ubuntu-latest'
        run: CGO_ENABLED=0 go build -ldflags '-s -w' -v -o ./dmp && tar zcf dmp.tgz dmp

      - name: release
        uses: softprops/action-gh-release@v1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          draft: true
          token: ${{ secrets.GH_TOKEN }}
          files: |
            ./*.tgz

  build-image:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -f ./docker/Dockerfile -t ${{ env.REGISTRY_SERVER_ADDRESS }}:${{ env.TAG }} -t ${{ env.REGISTRY_SERVER_ADDRESS }}:latest .
          docker push ${{ env.REGISTRY_SERVER_ADDRESS }}:${{ env.TAG }}
          docker push ${{ env.REGISTRY_SERVER_ADDRESS }}:latest
